script_dir= "example"

[scripts]

	[example1]
	EXAMPLE1_DIR="."
	EXAMPLE1_VALUE="applied"

	[example2]
	VAR="Hello World!"
	is_applied="test -f example2.tmp"
	apply="echo ${VAR} > example2.tmp"
	unapply="rm -vf example2.tmp"
