script_dir= "example"

[scripts]

	[example1]
	EXAMPLE1_DIR="."
	EXAMPLE1_VALUE="applied"

	[example2]
	VAR="Hello World!"
	is_applied_script="test -f example2.tmp"
	applied_script="echo ${VAR} > example2.tmp"
	unapply_script="rm -vf example2.tmp"
